version: '3.9'

services:
  frontend_nginx:
    restart: always
    image: demo_frontend_nginx:latest
    build:
      context: builds/nginx/demo/prod
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./front:/var/www/front:rw,cached


#  admin_nginx:
#    restart: always
#    image: zaberu_admin_nginx:latest
#    build:
#      context: builds/nginx/admin/prod
#      dockerfile: Dockerfile
#    environment:
#      - VUE_APP_API_URL
#      - VUE_APP_FRONTEND_URL
#    ports:
#      - 8880:80
#    volumes:
#      - ./admin:/var/www/admin:rw,cached
#    networks:
#      - backend
#      - admin
#
#  backend_node:
#    restart: always
#    image: zaberu_backend_node:latest
#    build:
#      context: builds/node/backend/dev
#      dockerfile: Dockerfile
#    environment:
#      - MYSQL_DATABASE
#      - MYSQL_USER
#      - MYSQL_PASSWORD
#      - VUE_APP_FRONTEND_URL
#      - VUE_APP_ADMIN_URL
#    #    expose:
#    #      - 8860
#    #      - 8080
#    #      - 3000
#    ports:
#      - 8860:3000
#      - 8080:8080
#    volumes:
#      - ./back:/var/www/backend:rw,cached
#    networks:
#      - backend
#
#  redis:
#    restart: always
#    image: redis:latest
#    expose:
#      - 6379
#    volumes:
#      - ./redis:/data:rw
#    networks:
#      - backend
#
#  mysql:
#    restart: always
#    image: mysql:5.7
#    environment:
#      - MYSQL_DATABASE
#      - MYSQL_USER
#      - MYSQL_PASSWORD
#      - MYSQL_ROOT_PASSWORD
#    #    expose:
#    #      - 3360
#    networks:
#      - backend
#    ports:
#      - 3360:3306
#    command: [ '--character-set-server=utf8mb4', '--default-authentication-plugin=mysql_native_password' ]
#
#networks:
#  backend:
#    driver: bridge
#  frontend:
#    driver: bridge
#  admin:
#    driver: bridge
